seed: 99102
render_process: True

data_name: null
data:
  task: null
  max_time: 300
  batch_size: 2
  white_background: True
  llffhold: 8
  time_subsample: 1
  disjoint_views: 0
  motion_blur: False
  with_dynamic_mask: False

model:
  name: 4dgs
  sh_degree: 3
  percent_dense: 0.01
  deformation:
    net_width: 64
    defor_depth: 1
    posebase_pe: 10
    scale_rotation_pe: 2
    opacity_pe: 2
    no_dx: False
    no_ds: False
    no_dr: False
    no_do: True
    no_dshs: True
    no_grid: False
    bounds: 1.6
    kplanes_config:
      grid_dimensions: 2
      input_coordinate_dim: 4
      output_coordinate_dim: 32
      resolution: [64, 64, 64, 25]
    multires: [1, 2, 4, 8]
    empty_voxel: False
    grid_pe: 0
    static_mlp: False

optimize:
  coarse_iterations: 3000
  fine_iterations: 30000
  plane_tv_weight: 0.0001
  time_smoothness_weight: 0.01
  l1_time_planes: 0.0001
  position_lr_init: 0.00016
  position_lr_final: 0.0000016
  position_lr_delay_mult: 0.01
  position_lr_max_steps: 25000
  deformation_lr_init: 0.00016
  deformation_lr_final: 0.000016
  deformation_lr_delay_mult: 0.01
  grid_lr_init: 0.0016
  grid_lr_final: 0.00016
  feature_lr: 0.0025
  opacity_lr: 0.05
  scaling_lr: 0.005
  rotation_lr: 0.001
  lambda_dssim: 0.
  lambda_event: 0.
  lambda_preg: 0.
  lambda_creg: 0.

densify:
  opacity_reset_interval: 20000
  densification_interval: 200
  densify_from_iter: 500
  densify_until_iter: 15000
  densify_grad_threshold_coarse: 0.0002
  densify_grad_threshold_fine_init: 0.0002
  densify_grad_threshold_after: 0.0002
  pruning_from_iter: 500
  pruning_interval: 100
  opacity_threshold_coarse: 0.005
  opacity_threshold_fine_init: 0.005
  opacity_threshold_fine_after: 0.005

ev_densify:
  apply_ev_densify: False
  ev_thr: 1
  knn: 3
  num_depths: 100
  downsample_scale: 2
  float_thr: 5
  num_candidates: 2000
  densify_from_iter: 500
  densify_until_iter: 15000
  densify_interval: 200
